name: gonnamake
markdown: redcarpet
highlighter: pygments
safe: true
lsi: false
source: ./
exclude: [node_modules, styl]
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/:num"
permalink: none

authors:
  iraycd:
    name: Ray Ch
    username: iraycd
    avatar: 0
    email: ray@ninjaas.com
    web: http://iraycd.com
    twitter: iraycd
    github: iraycd
